% author: mferhata
% reverse the sign of the following methods as they measure simplicity rather than
% complexity
reverseds = [   "10_k_regularity" ...
                "16_convexA" ...
                "18_convexJ" ...
                "19_convexL" ...
                "20_convexificationArea" ...
                "21_convexificationRevArea" ...
                ];
